indentation corrected

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -21,7 +21,7 @@ jobs:
       - name: Set up Node.js
         uses: actions/setup-node@v3
         with:
-          node-version: '20.x.x'
+          node-version: '20.x.x'  # Asegúrate de usar una versión compatible y estable.
 
       - name: Install dependencies
         run: npm install
@@ -39,6 +39,13 @@ jobs:
           name: build-artifact  
           path: dist/ats-project/browser 
 
+      - name: Verify artifact upload
+        run: |
+          if ! ls dist/ats-project/browser; then
+            echo "Artifact not found!"
+            exit 1
+          fi
+
   deploy:
     runs-on: ubuntu-latest
     needs: build
@@ -53,4 +60,4 @@ jobs:
 
       - name: Deploy to GitHub Pages
         id: deployment
-        uses: actions/deploy-pages@v3
+        uses: actions/deploy-pages@v4
